// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {region} from '../models';
import {session} from '../models';
import {preset} from '../models';

export function AddBookmark():Promise<region.Bookmark>;

export function AddFileToSession(arg1:string):Promise<session.Session>;

export function BatchExport(arg1:Array<string>,arg2:string):Promise<number>;

export function BrowseForExportDir():Promise<string>;

export function BrowseForFile():Promise<string>;

export function BrowseForMPV():Promise<string>;

export function DeleteRegion(arg1:string):Promise<void>;

export function ExportRegion(arg1:string):Promise<string>;

export function GetInProgressRegions():Promise<Array<region.InProgressRegion>>;

export function GetMPVPath():Promise<string>;

export function GetMPVStatus():Promise<boolean>;

export function GetOpenTags():Promise<Array<string>>;

export function GetPresets():Promise<Array<preset.Preset>>;

export function GetRegions():Promise<Array<region.Entry>>;

export function GetSession():Promise<session.Session>;

export function GetTimePos():Promise<number>;

export function ListSessions():Promise<Array<session.Session>>;

export function LoadSession(arg1:string):Promise<session.Session>;

export function MergeRegions(arg1:string,arg2:string):Promise<void>;

export function NewSession(arg1:string):Promise<session.Session>;

export function NudgeRegion(arg1:string,arg2:string,arg3:number):Promise<void>;

export function OpenFile(arg1:string):Promise<void>;

export function Pause():Promise<void>;

export function Play():Promise<void>;

export function PressTag(arg1:string,arg2:string,arg3:string):Promise<region.Region>;

export function RemoveFileFromSession(arg1:string):Promise<session.Session>;

export function SearchRegions(arg1:Array<string>,arg2:string,arg3:string,arg4:number,arg5:number):Promise<Array<region.Entry>>;

export function Seek(arg1:number,arg2:boolean):Promise<void>;

export function SeekToEntry(arg1:string):Promise<void>;

export function SetActiveFile(arg1:number):Promise<void>;

export function SetRegionTime(arg1:string,arg2:string,arg3:number):Promise<void>;

export function SetSpeed(arg1:number):Promise<void>;

export function StopPlayer():Promise<void>;

export function TestIPC():Promise<string>;

export function UpdateNotes(arg1:string,arg2:string):Promise<void>;
