// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function BrowseForFile() {
  return window['go']['main']['App']['BrowseForFile']();
}

export function GetMPVStatus() {
  return window['go']['main']['App']['GetMPVStatus']();
}

export function GetPresets() {
  return window['go']['main']['App']['GetPresets']();
}

export function GetTimePos() {
  return window['go']['main']['App']['GetTimePos']();
}

export function OpenFile(arg1) {
  return window['go']['main']['App']['OpenFile'](arg1);
}

export function StopPlayer() {
  return window['go']['main']['App']['StopPlayer']();
}
