// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddBookmark() {
  return window['go']['main']['App']['AddBookmark']();
}

export function AddFileToSession(arg1) {
  return window['go']['main']['App']['AddFileToSession'](arg1);
}

export function BrowseForFile() {
  return window['go']['main']['App']['BrowseForFile']();
}

export function BrowseForMPV() {
  return window['go']['main']['App']['BrowseForMPV']();
}

export function DeleteRegion(arg1) {
  return window['go']['main']['App']['DeleteRegion'](arg1);
}

export function ExportRegion(arg1) {
  return window['go']['main']['App']['ExportRegion'](arg1);
}

export function GetMPVPath() {
  return window['go']['main']['App']['GetMPVPath']();
}

export function GetMPVStatus() {
  return window['go']['main']['App']['GetMPVStatus']();
}

export function GetOpenTags() {
  return window['go']['main']['App']['GetOpenTags']();
}

export function GetPresets() {
  return window['go']['main']['App']['GetPresets']();
}

export function GetRegions() {
  return window['go']['main']['App']['GetRegions']();
}

export function GetSession() {
  return window['go']['main']['App']['GetSession']();
}

export function GetTimePos() {
  return window['go']['main']['App']['GetTimePos']();
}

export function ListSessions() {
  return window['go']['main']['App']['ListSessions']();
}

export function LoadSession(arg1) {
  return window['go']['main']['App']['LoadSession'](arg1);
}

export function NewSession(arg1) {
  return window['go']['main']['App']['NewSession'](arg1);
}

export function OpenFile(arg1) {
  return window['go']['main']['App']['OpenFile'](arg1);
}

export function Pause() {
  return window['go']['main']['App']['Pause']();
}

export function Play() {
  return window['go']['main']['App']['Play']();
}

export function PressTag(arg1, arg2, arg3) {
  return window['go']['main']['App']['PressTag'](arg1, arg2, arg3);
}

export function RemoveFileFromSession(arg1) {
  return window['go']['main']['App']['RemoveFileFromSession'](arg1);
}

export function Seek(arg1, arg2) {
  return window['go']['main']['App']['Seek'](arg1, arg2);
}

export function SeekToEntry(arg1) {
  return window['go']['main']['App']['SeekToEntry'](arg1);
}

export function SetActiveFile(arg1) {
  return window['go']['main']['App']['SetActiveFile'](arg1);
}

export function SetSpeed(arg1) {
  return window['go']['main']['App']['SetSpeed'](arg1);
}

export function StopPlayer() {
  return window['go']['main']['App']['StopPlayer']();
}

export function TestIPC() {
  return window['go']['main']['App']['TestIPC']();
}

export function UpdateNotes(arg1, arg2) {
  return window['go']['main']['App']['UpdateNotes'](arg1, arg2);
}
