// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {preset} from '../models';

export function BrowseForFile():Promise<string>;

export function BrowseForMPV():Promise<string>;

export function GetMPVPath():Promise<string>;

export function GetMPVStatus():Promise<boolean>;

export function GetPresets():Promise<Array<preset.Preset>>;

export function GetTimePos():Promise<number>;

export function OpenFile(arg1:string):Promise<void>;

export function StopPlayer():Promise<void>;

export function TestIPC():Promise<string>;
